version: '3.7'
services:
  api-server:
    build:
      context: .
      target: server
    environment:
      - API_PORT=3000
      - MOCK_RESPONSES
      - PG_HOST
      - PG_USER
      - PG_PASSWORD
      - PG_DATABASE
    ports:
      - 4000:3000
