version: '3.7'
services:
  postgres:
    build: ../test/postgres
    restart: always
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: