version: '3.7'
services:
  hasura:
    image: hasura/graphql-engine:v1.0.0-beta.6
    ports:
      - "8090:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://nix:postgres@postgres:5432/cexplorer
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  postgres:
    build: ../test/postgres
    restart: always
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_PASSWORD=postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
